# Generated by Django 5.0.1 on 2026-01-30 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/photos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='profiles/covers/')),
                ('bio', models.TextField(blank=True, help_text='Brief bio or tagline (max 500 characters)', max_length=500)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, help_text='Job title or role', max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone_primary', models.CharField(blank=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email_public', models.EmailField(blank=True, help_text='Public email (different from login email if needed)', max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Social media links in format: {"platform": "url"}')),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='Custom fields in format: [{"label": "", "value": "", "icon": ""}]')),
                ('show_profile_photo', models.BooleanField(default=True)),
                ('show_cover_photo', models.BooleanField(default=True)),
                ('show_save_contact_button', models.BooleanField(default=True)),
                ('show_share_button', models.BooleanField(default=True)),
                ('show_qr_code', models.BooleanField(default=True)),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('TEXT', 'Text Block'), ('LINK', 'Link'), ('LINK_GROUP', 'Link Group'), ('IMAGE', 'Image'), ('GALLERY', 'Image Gallery'), ('VIDEO', 'Video Embed'), ('DOCUMENT', 'Document'), ('HTML', 'Custom HTML')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.JSONField(default=dict, help_text='Content data structure varies by content_type')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'profile content',
                'verbose_name_plural': 'profile contents',
                'ordering': ['order'],
            },
        ),
    ]
