# Generated by Django 6.0.3 on 2026-03-10 18:04

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Max 500KB. JPG, PNG supported.', null=True, upload_to='profiles/covers/', validators=[profiles.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Max 500KB. JPG, PNG supported.', null=True, upload_to='profiles/photos/', validators=[profiles.models.validate_image_size]),
        ),
    ]
