# Generated by Django 5.0.1 on 2026-01-30 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('theme_type', models.CharField(choices=[('SYSTEM', 'System Theme'), ('CUSTOM', 'Custom Theme')], default='SYSTEM', max_length=20)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='themes/previews/')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#4f46e5', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#0f172a', max_length=7)),
                ('accent_color', models.CharField(default='#818cf8', max_length=7)),
                ('background_type', models.CharField(choices=[('SOLID', 'Solid Color'), ('GRADIENT', 'Gradient'), ('IMAGE', 'Image')], default='SOLID', max_length=20)),
                ('background_gradient', models.CharField(blank=True, help_text='CSS gradient value, e.g., "linear-gradient(135deg, #6366f1, #4f46e5)"', max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='themes/backgrounds/')),
                ('font_family_heading', models.CharField(default='Plus Jakarta Sans', max_length=100)),
                ('font_family_body', models.CharField(default='Inter', max_length=100)),
                ('border_radius', models.CharField(default='0.75rem', max_length=20)),
                ('card_shadow', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('custom_css', models.TextField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
                'ordering': ['name'],
            },
        ),
    ]
