# Generated by Django 5.0.1 on 2026-01-30 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cards', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAnalytics',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics_summary', serialize=False, to='organizations.organization')),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('total_cards', models.PositiveIntegerField(default=0)),
                ('active_cards', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('views_last_30_days', models.PositiveIntegerField(default=0)),
                ('top_cards', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'organization analytics',
                'verbose_name_plural': 'organization analytics',
            },
        ),
        migrations.CreateModel(
            name='UserAnalyticsSummary',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics_summary', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_unique_views', models.PositiveIntegerField(default=0)),
                ('total_contact_saves', models.PositiveIntegerField(default=0)),
                ('total_interactions', models.PositiveIntegerField(default=0)),
                ('views_last_30_days', models.PositiveIntegerField(default=0)),
                ('views_previous_30_days', models.PositiveIntegerField(default=0)),
                ('views_trend_percentage', models.FloatField(default=0)),
                ('last_view_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user analytics summary',
                'verbose_name_plural': 'user analytics summaries',
            },
        ),
        migrations.CreateModel(
            name='DailyAnalyticsSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('contact_saves', models.PositiveIntegerField(default=0)),
                ('phone_clicks', models.PositiveIntegerField(default=0)),
                ('email_clicks', models.PositiveIntegerField(default=0)),
                ('website_clicks', models.PositiveIntegerField(default=0)),
                ('social_clicks', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('mobile_views', models.PositiveIntegerField(default=0)),
                ('desktop_views', models.PositiveIntegerField(default=0)),
                ('tablet_views', models.PositiveIntegerField(default=0)),
                ('top_countries', models.JSONField(default=dict)),
                ('top_cities', models.JSONField(default=dict)),
                ('top_referrers', models.JSONField(default=dict)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='cards.nfccard')),
            ],
            options={
                'verbose_name': 'daily analytics summary',
                'verbose_name_plural': 'daily analytics summaries',
                'ordering': ['-date'],
                'unique_together': {('card', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProfileAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('VIEW', 'Profile View'), ('CONTACT_SAVE', 'Save Contact'), ('PHONE_CLICK', 'Phone Click'), ('EMAIL_CLICK', 'Email Click'), ('WEBSITE_CLICK', 'Website Click'), ('SOCIAL_CLICK', 'Social Link Click'), ('SHARE', 'Profile Share'), ('QR_DOWNLOAD', 'QR Code Download'), ('CUSTOM_LINK_CLICK', 'Custom Link Click')], default='VIEW', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional interaction data (e.g., which social link was clicked)')),
                ('visitor_ip_hash', models.CharField(blank=True, help_text='Hashed IP address for unique visitor counting', max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('referrer', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('DESKTOP', 'Desktop'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='cards.nfccard')),
            ],
            options={
                'verbose_name': 'profile analytics',
                'verbose_name_plural': 'profile analytics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['card', 'interaction_type'], name='analytics_p_card_id_14f2b1_idx'), models.Index(fields=['card', 'timestamp'], name='analytics_p_card_id_ee1a28_idx')],
            },
        ),
    ]
