# Generated by Django 5.0.1 on 2026-01-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_google_login', models.BooleanField(default=True, help_text='Enable/Disable Google Login button on login/register pages.')),
            ],
            options={
                'verbose_name': 'Authentication Settings',
                'verbose_name_plural': 'Authentication Settings',
            },
        ),
    ]
