# Generated by Django 6.0.1 on 2026-02-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='Unique username for profile URL. Letters, numbers, and underscores only.', max_length=50, null=True, unique=True, verbose_name='username'),
        ),
    ]
