# Generated by Django 5.0.1 on 2026-01-30 10:47

import cards.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_uid', models.CharField(help_text='Physical NFC card unique identifier', max_length=50, unique=True)),
                ('url_slug', models.SlugField(default=cards.models.generate_card_slug, help_text='Unique URL slug for public profile access', unique=True)),
                ('custom_css', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Activation'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False, help_text='If true, card requires password to view')),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('hide_from_search', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='themes.theme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NFC card',
                'verbose_name_plural': 'NFC cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cards', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_assignments', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cards.nfccard')),
            ],
            options={
                'verbose_name': 'card assignment',
                'verbose_name_plural': 'card assignments',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
