# Generated by Django 6.0.1 on 2026-02-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfccard',
            name='card_uid',
            field=models.CharField(blank=True, help_text='Physical NFC card unique identifier (optional)', max_length=50, null=True, unique=True),
        ),
    ]
