# Generated by Django 6.0.1 on 2026-02-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_make_card_uid_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfccard',
            name='url_slug',
            field=models.SlugField(blank=True, help_text='Unique URL slug for public profile access (auto-generated from username)', unique=True),
        ),
    ]
