# Generated by Django 5.0.1 on 2026-02-02 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('standard', 'Standard PVC - ₹499'), ('premium', 'Premium Matte - ₹799'), ('metal', 'Metal Hybrid - ₹1,299'), ('wood', 'Eco Wood - ₹999')], default='standard', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_design', models.ImageField(blank=True, help_text='Upload your custom design/logo (optional)', null=True, upload_to='orders/designs/')),
                ('custom_text', models.CharField(blank=True, help_text='Name or text to print on card', max_length=100)),
                ('shipping_address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Special instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card Order',
                'verbose_name_plural': 'Card Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
