# Generated by Django 5.0.1 on 2026-02-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardorder',
            name='card_type',
            field=models.CharField(choices=[('standard', 'Standard PVC - ₹449'), ('premium', 'Metallic Premium - ₹649')], default='standard', max_length=20),
        ),
    ]
