# Generated by Django 5.0.1 on 2026-02-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cardorder_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardorder',
            name='card_type',
            field=models.CharField(choices=[('white_pvc', 'White PVC Card - ₹449'), ('pink_pvc', 'Pink PVC Card - ₹449'), ('metallic', 'Metallic Premium Card - ₹649')], default='white_pvc', max_length=20),
        ),
    ]
